charts/ztka/README.md
charts/ztka/templates/_helpers.tpl
charts/ztka/values.yaml
docs/DEVELOPMENT.md
examples/values.domains.yaml

Rename `domain.host` to `domain.root` in `values.yaml`. The actual name to be replaced is still to be finalized. Started this PR just to have a discussion around it.
No

Switch from `domain.host` to new format

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template on GitHub to include running helm docs
Nope

Update PR todo list to include running `helm-docs`

---

examples/values.aks.yaml

This is AKS customized values.yaml file.
None

Add examples/values.aks.yaml file

---

CONTRIBUTING.md

Initial version of CONTRIBUTING.md. @techmaharaj feel free to make and updates on the same branch.
-

Add CONTRIBUTING docs

---

charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- Version bump for Dashboard and chart version update
- No

Release v0.1.1

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

Switch to paralus v0.1.2

---

charts/ztka/Chart.yaml
charts/ztka/README.md

Previous version is broken, bumping to release new version.
- Bump chart version

Bump chart version

---

charts/ztka/templates/job-kratos-hooks.yaml

Cleanup pod for kratos restart on success

Cleanup pod for kratos restart on success

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

Release 0.1.4

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- v0.1.7 release with few bug fixes
- No

v0.1.7 release 

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- update images for paralus, dashboard and changelog for release
- No

update images, chart versions and changelog

---

.github/workflows/ci.yaml
CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/README.md.gotmpl
charts/ztka/values.yaml
examples/values.dev-eks.yaml
examples/values.dev-generic.yaml
examples/values.elasticsearch.yaml
examples/values.host-hetwork.yaml

- Added chart upgrade document and more information of chart usage in README
- Updated helm-docs version to latest in CI
- Added an example elasticsearch values.yaml file
NONE

Add upgrading document in REAME

---

.github/workflows/release.yml

- add fluent helm chart to dependency
- No

add fluent helm chart to dependency

---

CONTRIBUTING.md

- added dco terms to contributing.md
- No

added dco terms to contributing.md

---

CHANGELOG.md
charts/ztka/README.md
charts/ztka/templates/_helpers.tpl
charts/ztka/templates/configmap-kratos-hooks.yaml
charts/ztka/templates/configmap-kratos.yaml
charts/ztka/templates/service-paralus.yaml
charts/ztka/values.yaml

- Added new webhook to after-login event to record events into paralus
- Original issue: [61](https://github.com/paralus/paralus/issues/61)
- Part of [111](https://github.com/paralus/paralus/pull/111)

added webhook to after-login event

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

Signed-off-by: Nirav Parikh <nir.parikh05@gmail.com>
- updated app versions and changelog for v0.2.0 release
- No

updated app versions and changelog for v0.2.0 release

---

.github/workflows/release.yml
CHANGELOG.md
charts/ztka/Chart.lock
charts/ztka/Chart.yaml
charts/ztka/README.md

Signed-off-by: Nirav Parikh <nir.parikh05@gmail.com>
- updated bitnami repository for postgres and contour
- No

updated bitnami repository for postgres and contour

---

CHANGELOG.md
charts/ztka/Chart.lock
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/templates/NOTES.txt
charts/ztka/values.yaml
docs/DEVELOPMENT.md

Upgrade Kratos dependency chart to Krato version v0.10.1
https://github.com/paralus/paralus/issues/92

Upgrade Kratos to v0.10.1

---

CHANGELOG.md
charts/ztka/Chart.lock
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

Signed-off-by: Nirav Parikh <nir.parikh05@gmail.com>
- updated images and changelogs for v0.2.1 release
- No

updated images and changelogs for v0.2.1 release

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- updates to paralus, dashboard, relay versions and changelogs for v0.2.2 release
- No

updates to paralus, dashboard, relay versions and changelogs 

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/templates/deployment-relay.yaml
charts/ztka/values.yaml

- updated paralus, dashboard, relay app versions and changelogs for v0.2.3 release
- No

chore: updated paralus, dashboard, relay app versions and changelogs

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- updated images for v0.2.4 release
-

updated images for v0.2.4 release

---

charts/ztka/README.md
charts/ztka/templates/job-kratos-hooks.yaml
charts/ztka/templates/job-paralus-post-install-analytics.yaml
charts/ztka/templates/job-paralus-post-upgrade-analytics.yaml
charts/ztka/templates/job-paralus-pre-upgrade-analytics.yaml
charts/ztka/values.yaml

- Added `hooks.enable` flag to control jobs that depend on helm hooks.
- No

Helm hooks enable flag

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- Updated dependency versions and docs
https://github.com/paralus/paralus/pull/246
https://github.com/paralus/relay/pull/74

chore: updated deps and docs

---

CHANGELOG.md
charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- updated dependencies and chart version
- https://github.com/paralus/dashboard/pull/216
- https://github.com/paralus/paralus/pull/260
- https://github.com/paralus/relay/pull/89

chore: updated dependencies and chart version

---

charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

- updated release versions for v0.2.7
-

chore(deps): updated release versions for v0.2.7

---

charts/ztka/Chart.yaml
charts/ztka/README.md
charts/ztka/values.yaml

-updated release versions for v0.2.9
-

chore(deps): updated release versions for v0.2.9
